# -*- coding: utf-8 -*-
"""EAI6010_Assignment6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlbnqLtX4jL9faHai92tNBazH0i5fqqd
"""
!pip install streamlit


import streamlit as st
import pandas as pd
import spacy
from textblob import TextBlob

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Streamlit App
st.title("Airbnb Listing NLP Analyzer")

# File uploader
uploaded_file = st.file_uploader("Upload Airbnb Listings CSV", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Select column for analysis
    text_column = st.selectbox("Select the column with property descriptions", df.columns)

    # Process descriptions
    if st.button("Analyze Descriptions"):
        entity_results = []
        sentiment_results = []

        for text in df[text_column].dropna():
            doc = nlp(text)
            entities = [(ent.text, ent.label_) for ent in doc.ents]
            sentiment = TextBlob(text).sentiment.polarity

            entity_results.append(entities)
            sentiment_results.append(sentiment)

        # Add results to DataFrame
        df["Entities"] = entity_results
        df["Sentiment"] = sentiment_results

        # Display results
        st.write("### Processed Data:")
        st.dataframe(df)

        # Option to download results
        df.to_csv("airbnb_nlp_results.csv", index=False)
        st.download_button("Download Processed Data", "airbnb_nlp_results.csv")

st.write("Upload an Airbnb dataset with textual property descriptions to analyze entities and sentiment!")
