# -*- coding: utf-8 -*-
"""Module6_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXDHEioaXahx95ytGMHTBaaUCnMXv6fR
"""

# Import necessary libraries
from google.colab import files
from fastai.text.all import load_learner

# 🔹 STEP 1: Manually upload the model file
print("📤 Upload `imdb_sentiment_model.pkl` from your local machine...")
uploaded = files.upload()  # Opens a file upload dialog

# Define model path
model_path = "imdb_sentiment_model.pkl"  # Since it's uploaded to Colab's /content/
print(f"✅ Model uploaded successfully: {model_path}")

# 🔹 STEP 2: Load the Model
print("📥 Loading the model...")
model = load_learner(model_path)
print("✅ Model loaded successfully!")

# 🔹 STEP 3: Test the Model with a Sample Review
review = "This movie was absolutely fantastic! I loved the acting and storyline."
prediction, _, probs = model.predict(review)

# Display Results
sentiment = "Positive" if prediction == "pos" else "Negative"
confidence = probs.max().item()

print("\n🎬 Example Review:", review)
print(f"📝 Sentiment: {sentiment} (Confidence: {confidence:.2f})")

print("\n🎉 Process complete!")